# Generated by Django 5.0.3 on 2024-05-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('idVendedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
            ],
            options={
                'db_table': 'nombre_tabla_vendedores',
            },
        ),
        migrations.RenameField(
            model_name='avion',
            old_name='modelo',
            new_name='id_modelo',
        ),
        migrations.RenameField(
            model_name='modelo',
            old_name='nombre',
            new_name='marca',
        ),
    ]
