# Generated by Django 5.0.3 on 2024-05-30 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_vendedor_rename_modelo_avion_id_modelo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelo',
            old_name='idModelo',
            new_name='id_modelo',
        ),
    ]
