# Generated by Django 5.0.3 on 2024-06-04 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0004_cargo_comuna_empleado_genero_persona_provincia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id_sede', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=100)),
                ('cantidad_pisos', models.IntegerField()),
                ('cantidad_salas', models.IntegerField()),
                ('comuna', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'adrian_sede',
            },
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='codCargo',
        ),
        migrations.RemoveField(
            model_name='comuna',
            name='provincia',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='comuna',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='rut',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='provincia',
            name='region',
        ),
        migrations.RenameField(
            model_name='modelo',
            old_name='marca',
            new_name='nombre',
        ),
        migrations.DeleteModel(
            name='Avion',
        ),
        migrations.DeleteModel(
            name='Cargo',
        ),
        migrations.DeleteModel(
            name='Comuna',
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.DeleteModel(
            name='Provincia',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
