# Generated by Django 5.0.3 on 2024-06-12 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0006_cliente_delete_modelo_delete_sede'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Empleado',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='id_cliente',
            new_name='id_empleado',
        ),
        migrations.AlterModelTable(
            name='empleado',
            table='adrian_empleado',
        ),
    ]
