# Generated by Django 5.0.3 on 2024-06-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0007_rename_cliente_empleado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('apaterno', models.CharField(max_length=100)),
                ('amaterno', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
                ('numero_telefono', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=100)),
                ('Fec_nacimiento', models.CharField(max_length=100)),
                ('edad', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'adrian_cliente',
            },
        ),
    ]
