# Generated by Django 5.0.3 on 2024-06-16 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0008_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('sku', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('stock', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'adrian_producto',
            },
        ),
    ]
