# Generated by Django 5.0.3 on 2024-07-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0010_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('idProd', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.CharField(max_length=100)),
                ('imagen_sb', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('desc_corta', models.CharField(max_length=100)),
                ('cant_favoritos', models.IntegerField(blank=True, null=True)),
                ('cant_vistos', models.IntegerField(blank=True, null=True)),
                ('precio', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'adrian_productos',
            },
        ),
        migrations.DeleteModel(
            name='Imagen',
        ),
    ]
